---

version: "3"

tasks:
  default:
    desc: update zshrc,starship
    cmds:
      - rsync .zshrc ~/.zshrc
      - rsync starship.toml ~/.config/starship.toml
      - rsync k8s-lens-templates/*.yml ~/.k8slens/templates/ahorbach
      - rsync .xonshrc ~/.xonshrc
