# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "dev-vm"
    config.vm.network "private_network", ip: "192.168.56.120"
    config.vm.synced_folder "./", "/srv/"
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
        ansible.galaxy_role_file = "../../../ansible/roles.galaxy/requirements.yml"
  end
    config.vm.provision :docker
end
