{
 "title": "Apache Exporter",
 "description": "https://github.com/Lusitaniae/apache_exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Is up?",
   "type": "stat",
   "description": "critical if it is NOT",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apache_up" }
   ]
  },
  {
   "title": "Uptime total",
   "type": "gauge",
   "description": "total uptime of the apache service in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apache_uptime_seconds_total" }
   ]
  },
  {
   "title": "avg request duration",
   "type": "stat",
   "description": "apache_accesses_total counter / apache_duration_ms_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_duration_ms_total / apache_accesses_total"
    }
   ]
  },
  {
   "title": "apache version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apache_version" }
   ]
  }
 ]
}