{
 "title": "DB",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Binlog size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_binlog_cache_size"
    }
   ]
  },
  {
   "title": "mysql_exporter_scrapes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_exporter_scrape_errors_total[1m])",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Auth",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_global_status_acl_users", "legendFormat": "users" },
    {
     "expr": "mysql_global_status_acl_database_grants",
     "legendFormat": "database_grants"
    }
   ]
  }
 ]
}