# -*- mode: ruby -*-
# vi: set ft=ruby :

ssh_pub_key = File.readlines('../public_key').first.strip
 # Use empty value for this vairable if you don't know your adapter name
host_bridge_int = "en0: Wi-Fi (Wireless)" 
base_ip = '192.168.1.8'
# 192.168.1.83; 192.168.1.84
nodes_start_prefix = 3
nodes_count = 4

Vagrant.configure("2") do |config|
    (nodes_start_prefix..nodes_count).each do |i|
        config.vm.define "kworker#{i}" do |node|
            node.vm.box = "ubuntu/focal64"
            node.vm.hostname = "node-#{i}"
            node.vm.network "public_network",
                ip: "#{base_ip}#{i}",
                bridge: "#{host_bridge_int}"

            node.vm.provider :virtualbox do |v|
                v.name    = "k8s-node-#{i}"
                v.memory  = 1024
                v.cpus    = 1
                end
            node.vm.provision :shell, :inline => "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys"
            node.vm.provision "shell", path: "../scripts/common.sh"
        end
    end
end
