version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    # Development mode with hot reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app 