# -*- mode: ruby -*-
# vi: set ft=ruby :

ssh_pub_key = File.readlines('./public_key').first.strip
 # Use empty value for this vairable if you don't know your adapter name
host_bridge_int = "en0: Wi-Fi (Wireless)" 
base_ip = '192.168.1.8'
node_prefix = '1'

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "node-#{node_prefix}"
    
    config.vm.network "public_network",
        ip: "#{base_ip}#{node_prefix}",
        bridge: "#{host_bridge_int}"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "k8s-node-#{node_prefix}"
        vb.memory = 2048
        vb.cpus = 2
        end
    config.vm.provision :shell, :inline => "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys"
    config.vm.provision "shell", path: "./scripts/common.sh"
  end
