# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder "./", "/srv/"
  config.vm.network "private_network", type: "dhcp"
  # configure cpu,memory,videomemory,and enable vbox gui
  config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 4
      v.gui = true
      v.customize ["modifyvm", :id, "--vram", "128"]
  end
end
